GET http://localhost:8181/api/repositories
Accept: application/json


####
GET http://localhost:8181/api/repositories/5678
Accept: application/json


###
POST http://localhost:8181/api/repositories
Content-Type: application/json

{
    "id": "5678",
    "name": "Test Repo New name",
    "files": []
}