
version: '3'
services:
  mongo:
    image: mongo:5.0.7
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
  app:
    build: .
    ports:
      - 8181:8181
    depends_on:
      - mongo